[project]
name = "vanguard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.14.3",
    "fastparquet>=2026.5.0",
    "mwparserfromhell>=0.7.2",
    "notebook>=7.6.1",
    "numpy<2",
    "pandas==2.0.0",
    "pyarrow>=25.0.0",
    "pydantic>=2.13.4",
]
